### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'placeholder'

### ISSUE THREAD

**Issue by MayurDivate** [kundajelab/deeplift#88]
HI Avanti,

I used Tensorflow 2.0 to build the model and it was saved in h5 format.
But when I used convert_model_from_saved_files method as suggested in the tutorial, I get following error.

```
self._activation_vars = tf.placeholder(
AttributeError: module 'tensorflow' has no attribute 'placeholder'
```

Is it possible to use deeplift on Tensorflow 2.0 models ?

Best regards,
Mayur

**Comment by AvantiShri** [comment]
Hi Mayur,

Unfortunately I have not updated my code to work with tensorflow 2.0 yet.
But I think that if you saved your model in the keras format, then you can
safely load it with deeplift if you create a virtual environment that has
an earlier version of tensorflow.

**Comment by lastproxy** [comment]
does deeplift suppport tensorflow 2.0 now?
